name: Continuous Integration
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  push:
    branches:
      - develop
      - 'feature/**'
      - 'release/**'
env:
  PYTHON_VERSION: '3.9'

jobs:

  job-Unittest:
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: ${{ env.PYTHON_VERSION }}
    - name: Instalación de librerias y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest -v test/test_persona.py
    - name: Validar resultado con errores
      if: ${{ failure() }}
      env:
        MENSAJE_ERROR: Una o varias pruebas fallaron
      run: echo "::set-output name=respuesta::${MENSAJE_ERROR}"
    - name: Validar resultado sin errores
      if: ${{ success() }}
      env:
        MENSAJE_EXITO: Todas las pruebas fueron exitosas
      run: echo "::set-output name=respuesta::${MENSAJE_EXITO}"
    - name: Calculo de cubrimiento
      id: cubrimiento
      run: |
          coverage run -m unittest test/test_persona.py
          coverage report -m

  job-automerge:
    name: Automerge
    needs: job-Unittest
    if: ${{ github.ref }} == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Merge develop into main
        uses: "tukasz/direct-merge-action@develop"
        with:
          GITHUB_TOKEN: "${{ secrets.TOKEN }}"
          source-branch: develop
          target-branch: main