name: Pruebas AutoMerge Feature
on:
  push:
    branches:
      - 'feature/**'
env:
  PYTHON_VERSION: '3.8'

jobs:

  job-merge-develop-feature:
    name: Actualizaci贸n de feature con develop
    if: ${{ contains(github.event.head_commit.message, 'Azul') }}
    runs-on: ubuntu-latest
    steps:
      - name: Merge develop -> feature
        uses: "tukasz/direct-merge-action@master"
        with:
          GITHUB_TOKEN: "${{ secrets.TOKEN }}"
          source-branch: develop
          target-branch: ${{ github.ref }}

  job-Unittest:
    name: Pruebas
    needs: job-merge-feature-develop
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuraci贸n de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: ${{ env.PYTHON_VERSION }}
    - name: Instalaci贸n de librerias y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest discover -s tests -v
    - name: Validar resultado con errores
      if: ${{ failure() }}
      env:
        MENSAJE_ERROR: Una o varias pruebas fallaron
      run: echo "::set-output name=respuesta::${MENSAJE_ERROR}"
    - name: Validar resultado sin errores
      if: ${{ success() }}
      env:
        MENSAJE_EXITO: Todas las pruebas fueron exitosas
      run: echo "::set-output name=respuesta::${MENSAJE_EXITO}"
    - name: Calculo de cubrimiento
      id: cubrimiento
      run: |
          coverage run -m unittest discover -s tests -v
          coverage report -m

  job-merge-feature-develop:
    name: Actualizaci贸n de develop con feature
    needs: job-Unittest
    runs-on: ubuntu-latest
    steps:
      - name: Merge feature -> develop
        uses: "tukasz/direct-merge-action@master"
        with:
          GITHUB_TOKEN: "${{ secrets.TOKEN }}"
          source-branch: ${{ github.ref }}
          target-branch: develop